### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [wjp2013/the_room_of_exercises#4]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`Best-App-for-Mac.md`](https://github.com/wjp2013/the_room_of_exercises/blob/bd214bb498f39e123d7aa225232b4e6d87385f22/guides/Best-App-for-Mac.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by wjp2013** [comment]
@reitermarkus get it, tks
